const express = require('express')
const router = express.Router()
const AdminController = require('../controllers/AdminController')
const { checkAuth } = require('../middlewares/checkAuth')

router.get('/admin', checkAuth, AdminController.showAdmin)
router.get('/admin/usuarios', checkAuth, AdminController.getUserStats)
router.get('/admin/stats', checkAuth, AdminController.getDetailedStats)
router.get('/admin/usuarios-recentes', checkAuth, AdminController.getRecentUsers)
router.get('/admin/todos-usuarios', checkAuth, AdminController.getAllUsers)
router.get('/admin/musicas', checkAuth, AdminController.getAllMusics)
router.get('/admin/albuns', checkAuth, AdminController.getAllAlbums)
router.get('/admin/eventos', checkAuth, AdminController.getAllEvents)
router.get('/admin/pedidos-servico', checkAuth, AdminController.getAllServiceRequests)
router.get('/admin/propostas-servico', checkAuth, AdminController.getAllServiceProposals)
router.get('/admin/servicos', checkAuth, AdminController.getAllServices)
router.get('/admin/denuncias', checkAuth, AdminController.getAllReports)

router.put('/admin/suspender-usuario/:id', AdminController.suspendUser)
router.delete('/admin/deletar-musica/:id', AdminController.deleteMusic)
router.delete('/admin/deletar-album/:id', AdminController.deleteAlbum)
router.delete('/admin/deletar-musica/:id', AdminController.deleteMusic)
router.delete('/admin/deletar-evento/:id', AdminController.deleteEvent)
router.delete('/admin/deletar-proposta-servico/:id', AdminController.deleteService)
router.delete('/admin/deletar-pedido-servico/:id', AdminController.deleteServiceRequest)
router.put('/admin/resolver-denuncia/:id', AdminController.resolveReport)

module.exports = router